name: Publish
run-name: Publish ${{ github.ref_name }}

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: echo "VERSION=$(jq -r .version < deno.json)" >> $GITHUB_ENV
      - run: exit 1
        if: ${{ github.ref_name != env.VERSION }}
      - run: npx jsr publish
